// <auto-generated />
using System;
using BrickedUpBrickBuyer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrickedUpBrickBuyer.Migrations
{
    [DbContext(typeof(BrickedUpBrickBuyerContext))]
    [Migration("20240409035535_FirstOne")]
    partial class FirstOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrickedUpBrickBuyer.Models.Account", b =>
                {
                    b.Property<int>("customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_ID"));

                    b.Property<int?>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<int>("access_level")
                        .HasColumnType("int");

                    b.Property<int>("admin_ID")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salt")
                        .HasColumnType("int");

                    b.HasKey("customer_ID");

                    b.HasIndex("Customer_ID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BrickedUpBrickBuyer.Models.Customer", b =>
                {
                    b.Property<int>("Customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customer_ID"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("birth_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_of_residence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("recommendation1")
                        .HasColumnType("int");

                    b.Property<int>("recommendation2")
                        .HasColumnType("int");

                    b.Property<int>("recommendation3")
                        .HasColumnType("int");

                    b.Property<int>("recommendation4")
                        .HasColumnType("int");

                    b.Property<int>("recommendation5")
                        .HasColumnType("int");

                    b.HasKey("Customer_ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BrickedUpBrickBuyer.Models.LineItem", b =>
                {
                    b.Property<int>("line_item_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("line_item_ID"));

                    b.Property<int>("product_ID")
                        .HasColumnType("int");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<int>("transaction_ID")
                        .HasColumnType("int");

                    b.HasKey("line_item_ID");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("BrickedUpBrickBuyer.Models.Order", b =>
                {
                    b.Property<int>("transaction_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transaction_ID"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_of_transaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customer_ID")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("day_of_week")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("entry_mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("fraud")
                        .HasColumnType("bit");

                    b.Property<string>("shipping_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("time")
                        .HasColumnType("int");

                    b.Property<string>("type_of_card")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_of_transaction")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("transaction_ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BrickedUpBrickBuyer.Models.Product", b =>
                {
                    b.Property<int>("product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_ID"));

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img_link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("num_parts")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("primary_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("recommendation1")
                        .HasColumnType("int");

                    b.Property<int>("recommendation2")
                        .HasColumnType("int");

                    b.Property<int>("recommendation3")
                        .HasColumnType("int");

                    b.Property<int>("recommendation4")
                        .HasColumnType("int");

                    b.Property<int>("recommendation5")
                        .HasColumnType("int");

                    b.Property<string>("secondary_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("product_ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BrickedUpBrickBuyer.Models.Account", b =>
                {
                    b.HasOne("BrickedUpBrickBuyer.Models.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID");

                    b.Navigation("customer");
                });
#pragma warning restore 612, 618
        }
    }
}
